# prototype/windows/tests/Test-Resolver-Skeleton.ps1
#
# Test for run_onchange_resolve-deps.ps1.tmpl — the apply-time resolver.
# Renders the resolver against the real skeleton manifest via
# tests/lib/render-resolver.ps1 (real chezmoi apply into a sandbox), then asserts
# the emitted deps.ps1 + install-plan.ps1 have the expected shape:
#   - deps.ps1 exists, parses, begins with the GENERATED banner, imports Core.psm1,
#     calls dep_reset_missing, and contains a guarded
#     `if (have <tool>) { ... } else { dep_mark_missing <tool> }` block.
#   - install-plan.ps1 exists, parses as tab-rows, and topo order is valid: any
#     dependency (kubectl) precedes its dependent (helm).
#
# PASS/FAIL tally; exit 1 on any failure.
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$here = $PSScriptRoot

$script:fail = 0
function check {
    param([string] $Name, [bool] $Result)
    if ($Result) {
        Write-Host "ok: $Name"
    }
    else {
        Write-Host "FAIL: $Name"
        $script:fail = 1
    }
}

# Render against the real skeleton manifest.
$manifest = Join-Path $here '..' '.chezmoidata/packages.yaml'
$outDir = & (Join-Path $here 'lib/render-resolver.ps1') -Fixture $manifest
$outDir = ($outDir | Select-Object -Last 1).ToString().Trim()

$depsPath = Join-Path $outDir 'deps.ps1'
$planPath = Join-Path $outDir 'install-plan.ps1'

# ---- deps.ps1 assertions ----------------------------------------------------
check "deps.ps1 exists" (Test-Path -LiteralPath $depsPath)

$deps = if (Test-Path -LiteralPath $depsPath) { Get-Content -LiteralPath $depsPath -Raw } else { '' }

# Parses cleanly (no syntax errors).
$parseErrors = $null
$tokens = $null
[void][System.Management.Automation.Language.Parser]::ParseFile($depsPath, [ref]$tokens, [ref]$parseErrors)
check "deps.ps1 parses (no syntax errors)" (($null -eq $parseErrors) -or ($parseErrors.Count -eq 0))

check "deps.ps1 begins with GENERATED banner" ($deps -match '^# GENERATED by run_onchange_resolve-deps')
check "deps.ps1 imports Core.psm1" ($deps -match 'Core\.psm1')
check "deps.ps1 calls dep_reset_missing" ($deps -match '(?m)^dep_reset_missing\s*$')

# Guarded block for at least one manifest tool (kubectl): the have-guard and the
# else dep_mark_missing must both be present.
check "deps.ps1 has 'if (have kubectl) {' guard" ($deps -match 'if \(have kubectl\) \{')
check "deps.ps1 has 'dep_mark_missing kubectl' on else branch" ($deps -match '\} else \{ dep_mark_missing kubectl \}')

# ---- install-plan.ps1 assertions --------------------------------------------
check "install-plan.ps1 exists" (Test-Path -LiteralPath $planPath)

$planParseErrors = $null
$planTokens = $null
if (Test-Path -LiteralPath $planPath) {
    [void][System.Management.Automation.Language.Parser]::ParseFile($planPath, [ref]$planTokens, [ref]$planParseErrors)
}
check "install-plan.ps1 parses (no syntax errors)" (($null -eq $planParseErrors) -or ($planParseErrors.Count -eq 0))

# Parse the tab rows (skip comment/blank lines): name<TAB>mgr<TAB>src.
$planRows = @()
if (Test-Path -LiteralPath $planPath) {
    $planRows = Get-Content -LiteralPath $planPath |
        Where-Object { $_ -and ($_ -notmatch '^\s*#') } |
        ForEach-Object { , ($_ -split "`t") }
}
check "install-plan.ps1 has tab-delimited rows" ($planRows.Count -gt 0)

$order = @($planRows | ForEach-Object { $_[0] })
$kubectlIdx = $order.IndexOf('kubectl')
$helmIdx = $order.IndexOf('helm')
check "topo order valid: kubectl and helm both present" (($kubectlIdx -ge 0) -and ($helmIdx -ge 0))
check "topo order valid: kubectl precedes helm (needs-before-dependent)" (($kubectlIdx -ge 0) -and ($helmIdx -ge 0) -and ($kubectlIdx -lt $helmIdx))

# ---- tally ------------------------------------------------------------------
if ($script:fail -eq 0) {
    Write-Host "`nALL PASS"
}
else {
    Write-Host "`nFAILURES PRESENT"
}
exit $script:fail
