#!/usr/bin/env bash
# Test for the on-demand provisioner (`im`/`lm`, Task 20b) — unit-tests the
# zsh logic in dot_functions.zsh (listMissing/installMissing) in isolation,
# WITHOUT going through chezmoi/the resolver: a temp install-plan.sh fixture
# stands in for the resolver's real output, and $DEPS_OUT_DIR points `im`/`lm`
# at it (the same env knob run_onchange_resolve-deps.sh.tmpl writes with —
# see dot_functions.zsh's _dep_plan_path comment).
#
# Reconciliation this task performs (context for why this test exists):
# dot_functions.zsh's ifcmd/ifpkg/ifalias (legacy brew/rustup MANAGER
# bootstraps + jiratui) used to keep their OWN `missing` assoc-array and
# `reportMissing`/`listMissing`/`installMissing` trio, entirely separate from
# core.sh's new _DEP_MISSING_COUNT/_DEP_MISSING_LIST tally that the
# resolver-emitted deps.sh guards feed via dep_mark_missing. Task 20b
# re-plumbed ifcmd/ifpkg onto dep_mark_missing (keeping a separate
# _DEP_RECIPE map for the legacy install recipe, since install-plan.sh only
# covers manifest tools) so BOTH sources land in one tally, and rewrote
# listMissing/installMissing to read that unified tally + resolve recipes
# from install-plan.sh (manifest) and _DEP_RECIPE (legacy) — this test proves
# that reconciliation actually works end-to-end in a real zsh process.
#
# This is a zsh-only test (the code under test is zsh, not POSIX sh): unlike
# most other tests/*.sh here, there is no bash section — zsh is unavailable
# in git-bash on this machine, so this SKIPs there instead of failing; the
# controller runs this same script under WSL to exercise it for real.
#
# Mechanics note: every grep-based assertion uses the crash-proof pattern
# `rc=0; grep -q ... || rc=$?; check "name" "$rc"` rather than
# `grep -q ...; check "$?"` — under `set -eEuo pipefail`, a failing `grep -q`
# as its own statement would abort this script before `check` ever runs and
# reports FAIL; guarding it behind `||`/`&&` keeps the failure visible as a
# reported FAIL instead of a silent crash. See test-resolver-setup.sh for the
# same idiom.
set -eEuo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
UNIX_ROOT="$(cd "$HERE/.." && pwd)"
CORE_LIB="$UNIX_ROOT/dot_config/dotfiles/lib/core.sh"
FUNCTIONS_ZSH="$UNIX_ROOT/dot_functions.zsh"

fail=0
# check NAME RESULT — RESULT is 0 (pass) or nonzero (fail); no re-evaluation.
check() {
  if [ "$2" -eq 0 ]; then
    echo "ok: $1"
  else
    echo "FAIL: $1"
    fail=1
  fi
}

run_zsh_tests() {
  echo "--- zsh section ---"

  if ! command -v zsh >/dev/null 2>&1; then
    echo "SKIP: zsh not found on this machine — cannot exercise the zsh" \
      "provisioner logic here (controller runs this script under WSL)"
    return 0
  fi

  # Isolated fake HOME so $DEPS_OUT_DIR/install-plan.sh (the default path
  # _dep_plan_path resolves to) is fully test-controlled and never touches a
  # real machine's ~/.config/dotfiles.
  sandbox="$(mktemp -d)"
  trap 'rm -rf "$sandbox"' RETURN

  plan_dir="$sandbox/.config/dotfiles"
  mkdir -p "$plan_dir"
  plan="$plan_dir/install-plan.sh"

  # Topo order deliberately b-before-a (mirrors test-resolver-plan.sh's "a
  # needs b" fixture) plus a custom row whose SRC embeds a pipe, to prove the
  # tab-delimited read survives shell-hostile bytes in the last field.
  {
    printf '%s\n' '# GENERATED by run_onchange_resolve-deps — do not edit. Read by im (provisioner).'
    printf '%s\n' '# format: <name>\t<manager>\t<source-or-install-command>   (topological order)'
    printf 'b\tbrew\tb-src\n'
    printf 'a\tbrew\ta-src\n'
    printf 'foo\tcustom\techo hi | cat\n'
  } > "$plan"

  # present\tbrew\tpresent-src would also be in the plan in a real run, but is
  # deliberately omitted here: install-plan.sh only lists MANIFEST tools, and
  # a present tool never reaches dep_mark_missing in the first place — so
  # "present tool must not be printed" is exercised via the LEGACY path below
  # instead (_DEP_RECIPE can (in principle) hold a stale/present entry).

  # Drive im/lm from a real zsh SCRIPT FILE, not `zsh -c '...'`: zsh parses a
  # `-c` argument as one compound unit before executing any of it, so an
  # `alias im=installMissing` defined earlier in the SAME `-c` string is not
  # yet known when the parser reaches a later `im` line in that string ->
  # "command not found: im" even though sourcing succeeded. A real script
  # file (like a real ~/.zshrc) is read-then-executed incrementally, so
  # aliases defined by an earlier `source` are visible to later lines — this
  # matches how `im`/`lm` are actually invoked interactively. (Verified this
  # failure mode directly against WSL zsh 5.9 while authoring this test.)
  driver1="$sandbox/driver1.zsh"
  cat > "$driver1" <<EOF
. "$CORE_LIB"
. "$FUNCTIONS_ZSH"

dep_reset_missing
dep_mark_missing b
dep_mark_missing a
dep_mark_missing foo
dep_mark_missing legacy-tool

_DEP_RECIPE[legacy-tool]="custom:echo legacy-install"
# present-legacy is intentionally NOT dep_mark_missing-ed and NOT in
# _DEP_RECIPE — it stands in for "a manifest/legacy tool that is not
# currently missing at all" so it must never appear in DRY_RUN output.

echo "=== DRY_RUN im ==="
DRY_RUN=1 im

echo "=== lm ==="
lm
EOF

  rc=0
  out="$(DEPS_OUT_DIR="$plan_dir" zsh "$driver1" 2>&1)" || rc=$?
  check "im/lm zsh script ran without error" "$rc"

  echo "$out"

  # -- DRY_RUN im: must print each candidate command, in the documented
  #    order (legacy _DEP_RECIPE bootstraps first, then install-plan.sh in
  #    topo order: b before a), and must NOT prompt/eval. --
  rc=0
  printf '%s' "$out" | grep -q '> echo legacy-install' || rc=$?
  check "DRY_RUN im: legacy _DEP_RECIPE recipe (legacy-tool) resolved + printed" "$rc"

  rc=0
  printf '%s' "$out" | grep -q '> brew install b-src' || rc=$?
  check "DRY_RUN im: install-plan row b resolved + printed" "$rc"

  rc=0
  printf '%s' "$out" | grep -q '> brew install a-src' || rc=$?
  check "DRY_RUN im: install-plan row a resolved + printed" "$rc"

  rc=0
  printf '%s' "$out" | grep -Fq '> echo hi | cat' || rc=$?
  check "DRY_RUN im: custom row (foo) printed verbatim, pipe intact" "$rc"

  legacy_line=$(printf '%s\n' "$out" | grep -n '> echo legacy-install' | head -1 | cut -d: -f1)
  b_line=$(printf '%s\n' "$out" | grep -n '> brew install b-src' | head -1 | cut -d: -f1)
  a_line=$(printf '%s\n' "$out" | grep -n '> brew install a-src' | head -1 | cut -d: -f1)
  rc=0
  [ -n "$legacy_line" ] && [ -n "$b_line" ] && [ -n "$a_line" ] \
    && [ "$legacy_line" -lt "$b_line" ] && [ "$b_line" -lt "$a_line" ] || rc=1
  check "order: legacy bootstrap ($legacy_line) before b ($b_line) before a ($a_line)" "$rc"

  rc=0
  printf '%s' "$out" | grep -q 'present-legacy' && rc=1
  check "DRY_RUN im: a tool never marked missing is never printed" "$rc"

  rc=0
  printf '%s' "$out" | grep -qi 'Do you want to install' && rc=1
  check "DRY_RUN im: does not prompt" "$rc"

  # -- lm: lists the missing names --
  rc=0
  printf '%s' "$out" | grep -q '> b' || rc=$?
  check "lm: lists b as missing" "$rc"

  rc=0
  printf '%s' "$out" | grep -q '> a' || rc=$?
  check "lm: lists a as missing" "$rc"

  rc=0
  printf '%s' "$out" | grep -q '> foo' || rc=$?
  check "lm: lists foo as missing" "$rc"

  rc=0
  printf '%s' "$out" | grep -q '> legacy-tool' || rc=$?
  check "lm: lists legacy-tool as missing" "$rc"

  # -- separately: a currently-missing tool that a PRIOR install already
  #    satisfied (re-check-live-presence) must be skipped even though it's
  #    still in the missing tally — use a real, guaranteed-present command
  #    (`sh`) as the "name" to prove the live re-check, not just the tally
  #    membership check. --
  driver2="$sandbox/driver2.zsh"
  cat > "$driver2" <<EOF
. "$CORE_LIB"
. "$FUNCTIONS_ZSH"

dep_reset_missing
dep_mark_missing sh
_DEP_RECIPE[sh]="custom:echo should-not-run"

DRY_RUN=1 im
EOF

  rc=0
  out2="$(DEPS_OUT_DIR="$plan_dir" zsh "$driver2" 2>&1)" || rc=$?
  check "im/lm zsh script (driver2) ran without error" "$rc"

  rc=0
  printf '%s' "$out2" | grep -q 'should-not-run' && rc=1
  check "DRY_RUN im: skips a candidate that is live-present despite being in the tally" "$rc"

  # -- Finding 1 regression: apt/dpkg-checked tools must use a dpkg presence
  #    recheck, not the command-hash/executable check (apt packages like
  #    build-essential are not commands, so commands[$name] is always empty).
  #    Pre-seed _DPKG_STATUS so _ensure_dpkg_status's cache-populated guard
  #    ((( ${#_DPKG_STATUS} > 0 )) && return) treats it as already queried. --
  driver3="$sandbox/driver3.zsh"
  cat > "$driver3" <<EOF
. "$CORE_LIB"
. "$FUNCTIONS_ZSH"

dep_reset_missing
typeset -gA _DPKG_STATUS
_DPKG_STATUS[aptpkg]="install ok installed"
dep_mark_missing aptpkg
dep_mark_missing aptmiss

DRY_RUN=1 im
EOF

  plan_dpkg="$plan_dir/install-plan.sh"
  {
    printf '%s\n' '# GENERATED by run_onchange_resolve-deps — do not edit. Read by im (provisioner).'
    printf '%s\n' '# format: <name>\t<manager>\t<source-or-install-command>   (topological order)'
    printf 'aptpkg\tapt\taptpkg\n'
    printf 'aptmiss\tapt\taptmiss\n'
  } > "$plan_dpkg"

  rc=0
  out3="$(DEPS_OUT_DIR="$plan_dir" zsh "$driver3" 2>&1)" || rc=$?
  check "im/lm zsh script (driver3, dpkg-aware recheck) ran without error" "$rc"

  rc=0
  printf '%s' "$out3" | grep -Fq 'apt-get install -y aptpkg' && rc=1
  check "DRY_RUN im: dpkg-present apt tool (aptpkg) is skipped, not reinstalled" "$rc"

  rc=0
  printf '%s' "$out3" | grep -Fq 'sudo apt-get update && sudo apt-get install -y aptmiss' || rc=$?
  check "DRY_RUN im: dpkg-absent apt tool (aptmiss) is still printed for install" "$rc"
}

main() {
  run_zsh_tests
  exit "$fail"
}

main "$@"
